/**
 * Provider-neutral object storage contract (ADR 0005). Domain code depends on this
 * interface only; the S3-compatible adapter is selected by configuration.
 *
 * Keys are generated by the application (never taken from user-supplied filenames) and
 * objects are private; signed temporary URLs arrive with the Evidence Vault (Phase 10).
 */
export interface StorageService {
  putObject(input: { key: string; body: Uint8Array; contentType: string }): Promise<void>;
  deleteObject(key: string): Promise<void>;
  objectExists(key: string): Promise<boolean>;
  /** Cheap reachability probe for health checks. */
  ping(): Promise<void>;
}

/** Generate an opaque object key under a namespace, e.g. `evidence/2026/10/<uuid>`. */
export function generateObjectKey(namespace: string, now: Date = new Date()): string {
  if (!/^[a-z0-9-]+$/.test(namespace)) {
    throw new Error(`Invalid storage namespace: ${namespace}`);
  }
  const month = String(now.getUTCMonth() + 1).padStart(2, "0");
  return `${namespace}/${now.getUTCFullYear()}/${month}/${crypto.randomUUID()}`;
}
