import { z } from "zod";

/**
 * PEOS metric catalogue (05_ANALYTICS_METRICS.md "Metric Governance", ADR 0019).
 *
 * Every metric declares name, definition, formula, source, frequency, owner and caveats. Only
 * metrics that can be computed truthfully from persisted data are `available`; the remaining
 * specification KPIs are listed as `unavailable` with the reason and the phase that unlocks them,
 * so the catalogue is honest about what PEOS can and cannot measure yet.
 *
 * The catalogue lives in code, next to the calculators that implement it, so a stated formula
 * cannot drift from the computed one. Changes are versioned (`version`, `revised`) and reviewed
 * through git; the API serves it read-only.
 */
export const METRIC_CATEGORIES = [
  "projects",
  "evidence",
  "skills",
  "certifications",
  "goals",
  "ai",
  "architecture",
  "engineering",
] as const;

const nonBlank = z.string().trim().min(1);

export const metricDefinitionSchema = z
  .object({
    key: z.string().regex(/^[a-z]+(\.[a-z_]+)+$/, "dotted lower-case key"),
    name: nonBlank,
    category: z.enum(METRIC_CATEGORIES),
    definition: nonBlank,
    formula: nonBlank,
    source: z.array(nonBlank).min(1),
    frequency: nonBlank,
    owner: nonBlank,
    caveats: z.array(nonBlank).min(1),
    /**
     * count = single number; distribution = counts per bucket; ratio = 0–1 share with numerator and
     * denominator in the breakdown; score = 0–100 explained by components; matrix = counts per
     * pair of categories.
     */
    valueType: z.enum(["count", "distribution", "ratio", "score", "matrix"]),
    /** point_in_time = current state; period = depends on the dashboard date range. */
    temporal: z.enum(["point_in_time", "period"]),
    /** Where the spec names this metric. */
    specRef: nonBlank,
    /** Human-readable drill-down target (the UI maps the key to a filtered list). */
    drillDown: z.string().nullable(),
    availability: z.discriminatedUnion("status", [
      z.object({ status: z.literal("available") }),
      z.object({ status: z.literal("unavailable"), reason: nonBlank, plannedPhase: nonBlank }),
    ]),
    version: z.number().int().positive(),
    introduced: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    revised: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  })
  .strict();

export type MetricDefinition = z.infer<typeof metricDefinitionSchema>;

const PHASE2 = { version: 1, introduced: "2026-10-02", revised: "2026-10-02" } as const;
const PHASE3 = { version: 1, introduced: "2026-10-03", revised: "2026-10-03" } as const;
const ON_REQUEST = "On request — computed live from the database when the Command Center loads.";
const OWNER = {
  projects: "PEOS Projects domain (src/modules/projects)",
  evidence: "PEOS Evidence domain (src/modules/evidence)",
  skills: "PEOS Skills domain (src/modules/skills)",
  certifications: "PEOS Certifications domain (src/modules/certifications)",
};
const SCOPE = "Only records owned by the signed-in user are counted.";

const AVAILABLE = { status: "available" } as const;
const unavailable = (reason: string, plannedPhase: string) =>
  ({ status: "unavailable", reason, plannedPhase }) as const;

const definitions: MetricDefinition[] = [
  // ── Projects ──────────────────────────────────────────────────────────────
  {
    key: "projects.total",
    name: "Projects",
    category: "projects",
    definition: "Number of projects recorded in PEOS.",
    formula: "COUNT(projects) where status/health match the dashboard project filters",
    source: ["Project"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [SCOPE, "Includes every lifecycle state, archived included."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "01 §3 Project Intelligence",
    drillDown: "Projects list with the same filters",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "projects.active",
    name: "Active projects",
    category: "projects",
    definition:
      "Projects currently being worked on: lifecycle status Discovery, Architecture, Development or Validation.",
    formula: "COUNT(projects WHERE status IN (discovery, architecture, development, validation))",
    source: ["Project.status"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Status is maintained manually; a project counts as active until you change its status.",
      "Ideas, production/maintenance systems and archived projects are excluded (ADR 0018).",
    ],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "00 §4 KPI strip — Active Projects",
    drillDown: "Projects list filtered to the active lifecycle group",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "projects.production",
    name: "Production systems",
    category: "projects",
    definition: "Projects whose lifecycle status is Production or Maintenance.",
    formula: "COUNT(projects WHERE status IN (production, maintenance))",
    source: ["Project.status"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Reflects the status you recorded; PEOS does not verify deployments (Phase 9).",
    ],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "00 §4 KPI strip — Production Systems",
    drillDown: "Projects list filtered to the production lifecycle group",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "projects.completed_in_period",
    name: "Projects completed",
    category: "projects",
    definition: "Projects whose recorded completion date falls within the selected period.",
    formula: "COUNT(projects WHERE completed_at BETWEEN period.start AND period.end)",
    source: ["Project.completedAt"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Implements the spec's “Projects Shipped (30/90/365 days)” using the completion date you entered; projects without a completion date are not counted.",
      "Period boundaries are calendar days in UTC.",
    ],
    valueType: "count",
    temporal: "period",
    specRef: "00 §4 KPI strip — Projects Shipped (30/90/365 days)",
    drillDown: "Projects list filtered to completion dates in the period",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "projects.health_distribution",
    name: "Project health",
    category: "projects",
    definition:
      "Number of projects in each manually assessed health state: On track, At risk, Blocked, Not assessed.",
    formula: "COUNT(projects) GROUP BY health_status",
    source: ["Project.healthStatus"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Health is your manual assessment, not a computed score. The derived health score (schedule, blockers, milestones) arrives in Phase 3.",
      "“Not assessed” is shown explicitly rather than hidden.",
    ],
    valueType: "distribution",
    temporal: "point_in_time",
    specRef: "01 §3 Project Health; 08 Phase 2 “project health”",
    drillDown: "Projects list filtered to the selected health state",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "projects.lifecycle_distribution",
    name: "Projects by lifecycle status",
    category: "projects",
    definition: "Number of projects in each lifecycle status.",
    formula: "COUNT(projects) GROUP BY status",
    source: ["Project.status"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [SCOPE, "Status is maintained manually."],
    valueType: "distribution",
    temporal: "point_in_time",
    specRef: "05 Portfolio Analytics — active vs archived",
    drillDown: "Projects list filtered to the selected status",
    availability: AVAILABLE,
    ...PHASE2,
  },
  // ── Projects: Phase 3 — milestones, delivery, computed health, portfolio ───
  {
    key: "projects.delivery_rate",
    name: "Delivery rate",
    category: "projects",
    definition:
      "Share of milestones that are complete, among milestones that are either complete or past their planned date (spec 05 'completed milestones / planned milestones').",
    formula:
      "COUNT(completed) / (COUNT(completed) + COUNT(overdue)); overdue = open (planned/in progress/blocked) AND dueDate < today (UTC) AND project not archived; cancelled milestones excluded",
    source: ["Milestone.status", "Milestone.dueDate", "Project.status"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Shown as a ratio only when the denominator is at least 1; otherwise the state is insufficient_data (never 0%).",
      "Milestones not yet due and undated open milestones are neither delivered nor late, so they are excluded.",
      "Evaluated as of today (UTC calendar day); computed per project and across the portfolio.",
    ],
    valueType: "ratio",
    temporal: "point_in_time",
    specRef: "05 Project Metrics — Delivery Rate; ADR 0024",
    drillDown: "Milestones list: completed (status=completed) and overdue (overdue=true)",
    availability: AVAILABLE,
    version: 2,
    introduced: "2026-10-02",
    revised: "2026-10-03",
  },
  {
    key: "projects.milestones_total",
    name: "Milestones",
    category: "projects",
    definition: "Number of milestones recorded, in any status.",
    formula: "COUNT(milestones)",
    source: ["Milestone"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [SCOPE],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "08 Phase 3 — milestones; 04 Milestone",
    drillDown: "Milestones list (per project: projectId filter)",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.milestones_completed",
    name: "Completed milestones",
    category: "projects",
    definition: "Number of milestones with status completed (they always have a completion date).",
    formula: "COUNT(milestones WHERE status = completed)",
    source: ["Milestone.status"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [SCOPE, "Current state: counts every completed milestone regardless of when."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "05 Delivery Rate numerator",
    drillDown: "Milestones list filtered to status=completed",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.milestones_completed_in_period",
    name: "Milestones completed",
    category: "projects",
    definition: "Number of milestones whose completion date falls inside the selected period.",
    formula: "COUNT(milestones WHERE completedAt within period)",
    source: ["Milestone.completedAt"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [SCOPE, "Uses the recorded completion date, never updatedAt or audit time."],
    valueType: "count",
    temporal: "period",
    specRef: "00 §4 Momentum; 05 Delivery Rate",
    drillDown: "Milestones list filtered to completedFrom/completedTo",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.milestones_overdue",
    name: "Overdue milestones",
    category: "projects",
    definition:
      "Open milestones (planned, in progress or blocked) whose planned date is before today, in projects that are not archived.",
    formula:
      "COUNT(milestones WHERE status IN (planned, in_progress, blocked) AND dueDate < today AND project.status <> archived)",
    source: ["Milestone.status", "Milestone.dueDate", "Project.status"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Today is the current UTC calendar day; a milestone due today is not overdue.",
      "Undated milestones are never overdue.",
    ],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "00 §4 Priority panels — Overdue milestone",
    drillDown: "Milestones list filtered to overdue=true",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.milestones_blocked",
    name: "Blocked milestones",
    category: "projects",
    definition: "Milestones whose status is blocked.",
    formula: "COUNT(milestones WHERE status = blocked)",
    source: ["Milestone.status"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Blocked is set manually on the milestone; PEOS has no separate blocker model.",
    ],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "01 §3 Project Health — blockers; ADR 0024",
    drillDown: "Milestones list filtered to status=blocked",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.milestone_completion_trend",
    name: "Milestone completions over time",
    category: "projects",
    definition: "Milestones completed per calendar month inside the selected period.",
    formula: "COUNT(milestones) GROUP BY month(completedAt) WHERE completedAt within period",
    source: ["Milestone.completedAt"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [SCOPE, "Months without completions are real zeros.", "At most 120 months are shown."],
    valueType: "distribution",
    temporal: "period",
    specRef: "05 Delivery Rate; 00 §4 Momentum",
    drillDown: "Milestones list filtered to the month's completion dates",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.delivery_trend",
    name: "Project delivery trend",
    category: "projects",
    definition: "Projects completed per calendar month inside the selected period.",
    formula: "COUNT(projects) GROUP BY month(completedAt) WHERE completedAt within period",
    source: ["Project.completedAt"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Only the recorded completion date is used — never status changes, updatedAt or audit time.",
      "Months without completions are real zeros. At most 120 months are shown.",
    ],
    valueType: "distribution",
    temporal: "period",
    specRef: "00 §4 Required charts — Project delivery trend",
    drillDown: "Projects list filtered to the month's completion dates",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.health_score",
    name: "Computed project health",
    category: "projects",
    definition:
      "Transparent analytical health signal for one project (model project-health-v1): the equal-weight mean of its scored components, with every component explained.",
    formula:
      "mean(score of components with state scored); overall only when ≥ 2 components are scored; band: ≥ 75 good, 50–74 needs watching, < 50 poor; archived → not assessed",
    source: [
      "Project.targetDate",
      "Project.completedAt",
      "Project.status",
      "Milestone",
      "AuditLog (project and milestones)",
    ],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Independent of the manual health status, which it never changes (ADR 0023).",
      "Scope stability and issue severity have no data source yet, so every v1 score is partial.",
      "Not persisted: recomputed on request as of today (UTC); no history, so 'declining health' cannot be shown.",
    ],
    valueType: "score",
    temporal: "point_in_time",
    specRef: "01 §3 Project Health Score; ADR 0024",
    drillDown: "Project dossier, Health section (component breakdown)",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.health_component.schedule",
    name: "Health component: schedule",
    category: "projects",
    definition: "Whether the project meets its target date.",
    formula:
      "completed: 100 if completedAt ≤ targetDate else 50; open: 100 if targetDate ≥ today else 0; no targetDate → insufficient data",
    source: ["Project.targetDate", "Project.completedAt"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Uses the project's own dates; milestone dates are covered by the milestone component.",
    ],
    valueType: "score",
    temporal: "point_in_time",
    specRef: "01 §3 — schedule",
    drillDown: "Project dossier, Health section",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.health_component.milestones",
    name: "Health component: milestone completion",
    category: "projects",
    definition: "The project's delivery rate expressed as 0–100.",
    formula: "round(100 × delivery rate); no completed or overdue milestone → insufficient data",
    source: ["Milestone.status", "Milestone.dueDate"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [SCOPE],
    valueType: "score",
    temporal: "point_in_time",
    specRef: "01 §3 — milestone completion",
    drillDown: "Project dossier, Delivery section",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.health_component.blockers",
    name: "Health component: blockers",
    category: "projects",
    definition: "Whether any open milestone is blocked.",
    formula: "no open milestones → insufficient data; any blocked → 0; none blocked → 100",
    source: ["Milestone.status"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Deliberately conservative: one blocked milestone scores 0.",
      "The manual 'Blocked' health status is not read (the two signals stay independent).",
    ],
    valueType: "score",
    temporal: "point_in_time",
    specRef: "01 §3 — blockers",
    drillDown: "Milestones list filtered to the project and status=blocked",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.health_component.recent_activity",
    name: "Health component: recent activity",
    category: "projects",
    definition:
      "Whether the project or its milestones changed in PEOS in the last 30 days (active lifecycle stages only).",
    formula:
      "status not in discovery/architecture/development/validation → not applicable; ≥ 1 audit event in 30 days → 100; none → 0",
    source: ["AuditLog (project and milestone events)"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Measures recorded changes in PEOS, not engineering work done elsewhere.",
      "Presence only — the volume of activity is never treated as health.",
    ],
    valueType: "score",
    temporal: "point_in_time",
    specRef: "01 §3 — recent activity; 05 Project Activity",
    drillDown: "Project dossier, Activity section",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.health_component.scope_stability",
    name: "Health component: scope stability",
    category: "projects",
    definition: "Change in committed scope during a period (spec 05).",
    formula: "Requires a committed-scope baseline and scope-change history",
    source: ["Committed scope (not modelled)"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: ["Reported as unavailable in every health breakdown; never estimated."],
    valueType: "score",
    temporal: "period",
    specRef: "01 §3 — scope stability; 05 Scope Stability",
    drillDown: null,
    availability: unavailable(
      "PEOS does not record a committed-scope baseline; the spec does not define one.",
      "Specification decision required",
    ),
    ...PHASE3,
  },
  {
    key: "projects.health_component.issue_severity",
    name: "Health component: issue severity",
    category: "projects",
    definition: "Severity of open issues affecting the project.",
    formula: "Requires an issue data source",
    source: ["Issues (not modelled; integrations)"],
    frequency: "Per integration sync",
    owner: OWNER.projects,
    caveats: ["05: do not fabricate metrics when integrations are unavailable."],
    valueType: "score",
    temporal: "point_in_time",
    specRef: "01 §3 — issue severity",
    drillDown: null,
    availability: unavailable("PEOS has no issue tracking.", "Phase 9 — Engineering Analytics"),
    ...PHASE3,
  },
  {
    key: "projects.computed_health_distribution",
    name: "Projects by computed health",
    category: "projects",
    definition:
      "Number of projects in each computed health band, plus projects with insufficient data and archived projects (not assessed).",
    formula: "COUNT(projects) GROUP BY computed band (project-health-v1)",
    source: ["Computed project health"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Computed on request for every project; not stored.",
      "Not a judgement of the manual assessment — see the manual vs computed comparison.",
    ],
    valueType: "distribution",
    temporal: "point_in_time",
    specRef: "01 §3 Project Health Score; 08 Phase 3 portfolio charts",
    drillDown: "Computed health list filtered to the band",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.health_comparison",
    name: "Manual vs computed health",
    category: "projects",
    definition:
      "Projects counted by their manual health status and their computed health band together.",
    formula: "COUNT(projects) GROUP BY (healthStatus, computed band)",
    source: ["Project.healthStatus", "Computed project health"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Describes agreement and disagreement only; neither signal is treated as correct (ADR 0023).",
    ],
    valueType: "matrix",
    temporal: "point_in_time",
    specRef: "ADR 0023",
    drillDown: "Computed health list filtered to manual status and band",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.technology_usage",
    name: "Technology usage across projects",
    category: "projects",
    definition: "Number of projects using each technology, split by usage type.",
    formula:
      "COUNT(technology_usages) GROUP BY technology, usageType (one row per project–technology)",
    source: ["TechnologyUsage", "Technology"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [
      SCOPE,
      "Shows where a technology was used, not proficiency — no proficiency score is derived.",
      "Top 15 technologies by project count; the rest are summarised as 'Other technologies'.",
    ],
    valueType: "distribution",
    temporal: "point_in_time",
    specRef: "08 Phase 3 — technology mapping; 02 'a technology filters projects'",
    drillDown: "Projects list filtered to the technology (technologyId)",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.evidence_coverage",
    name: "Project evidence coverage",
    category: "projects",
    definition: "Projects with at least one linked evidence item, and projects without any.",
    formula: "COUNT(projects WITH ≥ 1 project_evidence), COUNT(projects WITHOUT)",
    source: ["ProjectEvidence"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [SCOPE, "Counts links, not evidence quality; verification is shown per project."],
    valueType: "distribution",
    temporal: "point_in_time",
    specRef: "08 Phase 3 — project evidence",
    drillDown: "Projects list filtered to hasEvidence=true / false",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.evidence_linked",
    name: "Project evidence",
    category: "projects",
    definition: "Evidence items linked to one project.",
    formula: "COUNT(evidence WHERE linked to the project)",
    source: ["ProjectEvidence", "Evidence"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [SCOPE],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "08 Phase 3 — project evidence",
    drillDown: "Evidence list filtered to the project (projectId)",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.evidence_verified",
    name: "Verified project evidence",
    category: "projects",
    definition: "Verified evidence items linked to one project.",
    formula: "COUNT(evidence WHERE linked to the project AND verified)",
    source: ["ProjectEvidence", "Evidence.verified"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [SCOPE, "Verification is recorded by the user (Phase 1)."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "08 Phase 3 — project evidence",
    drillDown: "Evidence list filtered to the project and verified=true",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.evidence_by_type",
    name: "Project evidence by type",
    category: "projects",
    definition: "Evidence items linked to one project, per evidence type.",
    formula: "COUNT(evidence WHERE linked to the project) GROUP BY type",
    source: ["ProjectEvidence", "Evidence.type"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: [SCOPE],
    valueType: "distribution",
    temporal: "point_in_time",
    specRef: "08 Phase 3 — project evidence",
    drillDown: "Evidence list filtered to the project and type",
    availability: AVAILABLE,
    ...PHASE3,
  },
  {
    key: "projects.blocked_time",
    name: "Blocked time",
    category: "projects",
    definition: "Time projects remain blocked (spec 05).",
    formula: "Requires the history of status changes",
    source: ["Status history (not recorded)"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: ["Never reconstructed from the audit log retroactively."],
    valueType: "count",
    temporal: "period",
    specRef: "05 Project Metrics — Blocked Time",
    drillDown: null,
    availability: unavailable(
      "PEOS records only the current status, not when it changed (ADR 0025).",
      "Specification decision required",
    ),
    ...PHASE3,
  },
  {
    key: "projects.portfolio_matrix",
    name: "Project portfolio matrix",
    category: "projects",
    definition: "Impact × technical complexity, bubble size = effort (spec 05).",
    formula: "Requires numeric impact, complexity and effort",
    source: ["Project impact/complexity/effort (not modelled)"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: ["Project.impact is free text; complexity and effort do not exist in spec 04."],
    valueType: "matrix",
    temporal: "point_in_time",
    specRef: "05 Visualization Catalog — Project Portfolio Matrix",
    drillDown: null,
    availability: unavailable(
      "Spec 04 defines no numeric impact, complexity or effort fields.",
      "Specification decision required",
    ),
    ...PHASE3,
  },
  {
    key: "projects.technology_heatmap",
    name: "Technology heatmap",
    category: "projects",
    definition: "Technologies × months, cell = meaningful usage (spec 05).",
    formula: "Requires dated technology usage",
    source: ["TechnologyUsage (undated)"],
    frequency: ON_REQUEST,
    owner: OWNER.projects,
    caveats: ["Usage months are never inferred from project dates."],
    valueType: "matrix",
    temporal: "period",
    specRef: "05 Technology Heatmap; 00 §4 Technology usage heatmap",
    drillDown: null,
    availability: unavailable(
      "Technology usage has no dates; spec 04 TechnologyUsage defines none.",
      "Specification decision required",
    ),
    ...PHASE3,
  },
  // ── Evidence ──────────────────────────────────────────────────────────────
  {
    key: "evidence.total",
    name: "Evidence items",
    category: "evidence",
    definition: "Number of evidence records, dated or not.",
    formula: "COUNT(evidence) where type/verified/origin match the dashboard evidence filters",
    source: ["Evidence"],
    frequency: ON_REQUEST,
    owner: OWNER.evidence,
    caveats: [SCOPE, "Counts records, not their quality or strength."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "00 §4 KPI strip — Evidence Items",
    drillDown: "Evidence list with the same filters",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "evidence.verified",
    name: "Verified evidence",
    category: "evidence",
    definition: "Evidence records you marked as verified against their source.",
    formula: "COUNT(evidence WHERE verified = true)",
    source: ["Evidence.verified"],
    frequency: ON_REQUEST,
    owner: OWNER.evidence,
    caveats: [
      SCOPE,
      "Verification is a manual confirmation; PEOS does not check sources automatically.",
    ],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "05 Career Metrics — Evidence Velocity (verified evidence)",
    drillDown: "Evidence list filtered to verified",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "evidence.velocity",
    name: "Evidence velocity",
    category: "evidence",
    definition:
      "Verified evidence items whose evidence date falls within the selected period (verified evidence per period).",
    formula:
      "COUNT(evidence WHERE verified = true AND date BETWEEN period.start AND period.end); previous period = the same number of days immediately before",
    source: ["Evidence.verified", "Evidence.date"],
    frequency: ON_REQUEST,
    owner: OWNER.evidence,
    caveats: [
      SCOPE,
      "Uses the evidence date you recorded, not the day it was entered in PEOS.",
      "Verification is current state: an item verified today counts in the period of its evidence date.",
      "Undated evidence is excluded and reported separately.",
      "A previous-period comparison is shown only for bounded periods and only when dated evidence exists before the period starts.",
    ],
    valueType: "count",
    temporal: "period",
    specRef: "05 Career Metrics — Evidence Velocity",
    drillDown: "Evidence list filtered to verified items dated in the period",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "evidence.undated",
    name: "Undated evidence",
    category: "evidence",
    definition: "Evidence records without an evidence date. They cannot appear on the timeline.",
    formula: "COUNT(evidence WHERE date IS NULL)",
    source: ["Evidence.date"],
    frequency: ON_REQUEST,
    owner: OWNER.evidence,
    caveats: [SCOPE, "PEOS never assigns a date on your behalf."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "00 §6 — missing data must be explicit",
    drillDown: "Evidence list filtered to undated items",
    availability: AVAILABLE,
    ...PHASE2,
  },
  // ── Skills ────────────────────────────────────────────────────────────────
  {
    key: "skills.total",
    name: "Skills",
    category: "skills",
    definition: "Number of skills recorded.",
    formula: "COUNT(skills) where category matches the dashboard skill filter",
    source: ["Skill"],
    frequency: ON_REQUEST,
    owner: OWNER.skills,
    caveats: [SCOPE, "A recorded skill is not a claim of proficiency."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "08 Phase 2 — skill snapshot",
    drillDown: "Skills list",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "skills.active",
    name: "Active skills",
    category: "skills",
    definition: "Skills marked active (ones you are currently tracking).",
    formula: "COUNT(skills WHERE active = true)",
    source: ["Skill.active"],
    frequency: ON_REQUEST,
    owner: OWNER.skills,
    caveats: [SCOPE],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "04 Skill.active",
    drillDown: "Skills list filtered to active",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "skills.with_target",
    name: "Skills with a target level",
    category: "skills",
    definition: "Skills for which you set a target level.",
    formula: "COUNT(skills WHERE target_level IS NOT NULL)",
    source: ["Skill.targetLevel"],
    frequency: ON_REQUEST,
    owner: OWNER.skills,
    caveats: [
      SCOPE,
      "Targets are goals, not current levels. Current levels are derived from evidence in Phase 4.",
    ],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "04 Skill.targetLevel",
    drillDown: "Skills list filtered to skills with a target",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "skills.with_evidence",
    name: "Skills with evidence",
    category: "skills",
    definition: "Skills linked to at least one evidence item.",
    formula: "COUNT(skills WHERE EXISTS skill_evidence)",
    source: ["Skill", "SkillEvidence"],
    frequency: ON_REQUEST,
    owner: OWNER.skills,
    caveats: [
      SCOPE,
      "Counts the existence of a link only — not its strength, recency or verification. It is NOT the spec's “Skill Coverage” (which needs a recency rule, Phase 4).",
    ],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "08 Phase 2 — skill snapshot; 00 §2.1 evidence over self-assessment",
    drillDown: "Skills list filtered to skills with evidence",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "skills.without_evidence",
    name: "Active skills without evidence",
    category: "skills",
    definition: "Active skills that have no linked evidence yet.",
    formula: "COUNT(skills WHERE active = true AND NOT EXISTS skill_evidence)",
    source: ["Skill.active", "SkillEvidence"],
    frequency: ON_REQUEST,
    owner: OWNER.skills,
    caveats: [SCOPE, "Indicates missing documentation, not missing ability."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "01 §2 Career Evidence; 00 §4 “What evidence did I create?”",
    drillDown: "Skills list filtered to active skills without evidence",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "skills.by_category",
    name: "Skills by category",
    category: "skills",
    definition: "Number of skills in each category you assigned (uncategorised shown explicitly).",
    formula: "COUNT(skills) GROUP BY category",
    source: ["Skill.category"],
    frequency: ON_REQUEST,
    owner: OWNER.skills,
    caveats: [SCOPE, "Categories are free text; spelling variants count separately."],
    valueType: "distribution",
    temporal: "point_in_time",
    specRef: "01 §6 Skill Registry — Category",
    drillDown: "Skills list filtered to the selected category",
    availability: AVAILABLE,
    ...PHASE2,
  },
  // ── Certifications ────────────────────────────────────────────────────────
  {
    key: "certifications.total",
    name: "Certifications",
    category: "certifications",
    definition: "Number of certifications recorded, in any status.",
    formula: "COUNT(certifications)",
    source: ["Certification"],
    frequency: ON_REQUEST,
    owner: OWNER.certifications,
    caveats: [SCOPE, "Certifications are evidence, not proof of production proficiency (01 §7)."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "01 §7 Certifications",
    drillDown: "Certifications list",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "certifications.expiry_distribution",
    name: "Certification expiry",
    category: "certifications",
    definition:
      "Certifications by expiry state: Valid, Expiring within 90 days, Expired, No expiry date. Revoked certifications are excluded.",
    formula:
      "COUNT(certifications WHERE status <> revoked) GROUP BY expiryState(expiry_date, today) — same rule as the certification list",
    source: ["Certification.expiryDate", "Certification.status"],
    frequency: ON_REQUEST,
    owner: OWNER.certifications,
    caveats: [
      SCOPE,
      "Today is the current UTC date.",
      "Uses the 90-day expiring window defined in Phase 1.",
    ],
    valueType: "distribution",
    temporal: "point_in_time",
    specRef: "01 §7 — expiring certifications chart",
    drillDown: "Certifications list filtered to the selected expiry state",
    availability: AVAILABLE,
    ...PHASE2,
  },
  {
    key: "certifications.expiring",
    name: "Certifications expiring",
    category: "certifications",
    definition: "Non-revoked certifications that expire within the next 90 days.",
    formula:
      "COUNT(certifications WHERE status <> revoked AND expiry_date BETWEEN today AND today + 90 days)",
    source: ["Certification.expiryDate", "Certification.status"],
    frequency: ON_REQUEST,
    owner: OWNER.certifications,
    caveats: [SCOPE, "Certifications without an expiry date never count as expiring."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "00 §4 Attention — Certification expiring",
    drillDown: "Certifications list filtered to expiring",
    availability: AVAILABLE,
    ...PHASE2,
  },
  // ── Specified but not yet computable ─────────────────────────────────────
  {
    key: "goals.active",
    name: "Active goals",
    category: "goals",
    definition: "Goals currently in progress.",
    formula: "COUNT(goals WHERE status = active)",
    source: ["Goal (not yet modelled)"],
    frequency: ON_REQUEST,
    owner: "PEOS Goals domain (Phase 5)",
    caveats: ["Goals do not exist yet."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "00 §4 KPI strip — Active Goals",
    drillDown: null,
    availability: unavailable(
      "The Goal entity is not part of the data model yet.",
      "Phase 5 — Goals & Roadmap",
    ),
    ...PHASE2,
  },
  {
    key: "skills.coverage",
    name: "Skill coverage",
    category: "skills",
    definition: "Percentage of target skills with recent evidence.",
    formula: "COUNT(target skills with evidence in the recency window) / COUNT(target skills)",
    source: ["Skill.targetLevel", "SkillEvidence", "Evidence.date"],
    frequency: ON_REQUEST,
    owner: OWNER.skills,
    caveats: ["Requires a defined recency window (skill freshness)."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "05 Career Metrics — Skill Coverage; 00 §4 KPI strip",
    drillDown: null,
    availability: unavailable(
      "“Recent” is not defined by the specification; skill freshness is Phase 4 work. “Skills with evidence” is shown instead, without a recency claim.",
      "Phase 4 — Skills & Career Intelligence",
    ),
    ...PHASE2,
  },
  {
    key: "skills.critical_gaps",
    name: "Critical skill gaps",
    category: "skills",
    definition: "Target skills whose evidence-derived level is far below target.",
    formula: "Requires evidence-derived current levels",
    source: ["Skill", "SkillEvidence"],
    frequency: ON_REQUEST,
    owner: OWNER.skills,
    caveats: ["Current skill levels are not stored and are not yet derived."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "00 §4 KPI strip — Critical Skill Gaps",
    drillDown: null,
    availability: unavailable(
      "Gap analysis needs evidence-derived levels (ADR 0013).",
      "Phase 4 — Skills & Career Intelligence",
    ),
    ...PHASE2,
  },
  {
    key: "skills.freshness",
    name: "Skill freshness",
    category: "skills",
    definition: "Time since a skill was last demonstrated.",
    formula: "today − MAX(evidence date) per skill",
    source: ["SkillEvidence", "Evidence.date"],
    frequency: ON_REQUEST,
    owner: OWNER.skills,
    caveats: ["Freshness scoring and decay are Phase 4 intelligence."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "05 Career Metrics — Skill Freshness",
    drillDown: null,
    availability: unavailable(
      "Freshness thresholds are not specified. The Command Center shows each skill's latest linked evidence date as a plain fact instead.",
      "Phase 4 — Skills & Career Intelligence",
    ),
    ...PHASE2,
  },
  {
    key: "evidence.production_ratio",
    name: "Production evidence ratio",
    category: "evidence",
    definition: "Production-linked evidence divided by total evidence.",
    formula: "COUNT(production-linked evidence) / COUNT(evidence)",
    source: ["Evidence"],
    frequency: ON_REQUEST,
    owner: OWNER.evidence,
    caveats: ["Descriptive indicator, not a quality judgment (05)."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "05 Career Metrics — Production Evidence Ratio",
    drillDown: null,
    availability: unavailable(
      "“Production-linked” is not defined (evidence type production_metric? linked to a production project?). Needs a specification decision.",
      "Specification decision required",
    ),
    ...PHASE2,
  },
  {
    key: "ai.experiments",
    name: "AI experiments",
    category: "ai",
    definition: "Number of AI experiments recorded.",
    formula: "COUNT(ai_experiments)",
    source: ["AIExperiment (not yet modelled)"],
    frequency: ON_REQUEST,
    owner: "PEOS AI Lab domain (Phase 6)",
    caveats: ["AI experiments do not exist yet."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "00 §4 KPI strip — AI Experiments",
    drillDown: null,
    availability: unavailable("The AI Lab is not built yet.", "Phase 6 — AI Lab"),
    ...PHASE2,
  },
  {
    key: "architecture.decisions",
    name: "Architecture decisions",
    category: "architecture",
    definition: "Number of architecture decision records.",
    formula: "COUNT(architecture_decisions)",
    source: ["ArchitectureDecision (not yet modelled)"],
    frequency: ON_REQUEST,
    owner: "PEOS Architecture domain (Phase 7)",
    caveats: ["ADRs inside PEOS do not exist yet."],
    valueType: "count",
    temporal: "point_in_time",
    specRef: "00 §4 KPI strip — Architecture Decisions",
    drillDown: null,
    availability: unavailable(
      "Architecture Intelligence is not built yet.",
      "Phase 7 — Architecture Intelligence",
    ),
    ...PHASE2,
  },
  {
    key: "engineering.technical_debt_trend",
    name: "Technical debt trend",
    category: "engineering",
    definition: "Change in recorded technical debt over time.",
    formula: "Requires an engineering data source",
    source: ["Integrations (not yet built)"],
    frequency: "Per integration sync",
    owner: "PEOS Engineering Analytics (Phase 9)",
    caveats: ["05: do not fabricate metrics when integrations are unavailable."],
    valueType: "count",
    temporal: "period",
    specRef: "00 §4 KPI strip — Technical Debt Trend",
    drillDown: null,
    availability: unavailable(
      "No engineering integration exists yet.",
      "Phase 9 — Engineering Analytics",
    ),
    ...PHASE2,
  },
];

/** Validated at module load: an invalid definition fails fast in every environment and test. */
export const METRIC_CATALOGUE: readonly MetricDefinition[] = Object.freeze(
  definitions.map((definition) => metricDefinitionSchema.parse(definition)),
);

const BY_KEY = new Map(METRIC_CATALOGUE.map((metric) => [metric.key, metric]));
if (BY_KEY.size !== METRIC_CATALOGUE.length) throw new Error("Duplicate metric keys in catalogue");

export type MetricKey = (typeof definitions)[number]["key"];

export function getMetric(key: string): MetricDefinition {
  const metric = BY_KEY.get(key);
  if (!metric) throw new Error(`Unknown metric: ${key}`);
  return metric;
}

export function availableMetrics(): MetricDefinition[] {
  return METRIC_CATALOGUE.filter((m) => m.availability.status === "available");
}
